gantt
    title inTIRE Project Schedule
    dateFormat  YYYY-MM-DD
    axisFormat  %m/%d/%y
    
    section Planning & Design
    .        :a1, 2025-09-13, 2025-11-20
    
    section Design
    .          :a2, 2025-09-21, 2025-10-05
    
    section Implementation
    .  :active, b1, 2025-10-06, 2025-12-07
    
    section Deployment
    .      :c1, 2025-11-16, 2025-11-29
    
    section Testing
    .         :d1, 2025-12-08, 2025-12-14
    
    section Maintenance
    .     :d2, 2025-12-08, 2025-12-12
    
    section Documentation
    .   :e1, 2025-09-13, 2025-12-14

    